version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: jk
      POSTGRES_PASSWORD: xkop
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app

volumes:
  pgdata:
